#!/bin/bash
set -o errexit -o pipefail

function show_usage() {
    >&2 echo "Enter dockerd process's namespaces(mount,pid,net,ipc,user,uts,cgroup)."
    >&2 echo ""
    >&2 echo "Usage:"
    >&2 echo "  ${0##*/} [OPTIONS] [CMD [ARGS...]]"
    >&2 echo ""
    >&2 echo "OPTIONS:"
    >&2 echo "  -i, --interactive                    Keep STDIN open even if not attached"
    >&2 echo "  -t, --tty                            Allocate a pseudo-TTY"
    >&2 echo ""
    >&2 echo "Note:"
    >&2 echo "  - If no any argument specified, it will run an interactive /bin/sh (implies '-i' and '-t')."
    >&2 echo ""
    exit 1
}

OPT_INTERACTIVE=""; OPT_TTY=""

while [[ $# -gt 0 ]]; do
    case $1 in
    -i|--interactive)
            OPT_INTERACTIVE=$1
            ;;
    -t|--tty)
            OPT_TTY=$1
            ;;
    --*)
            show_usage
            ;;
    -*i*|-*t*)
            [[ $1 == *i* ]] && OPT_INTERACTIVE=-i
            [[ $1 == *t* ]] && OPT_TTY=-t
            [[ ! $1 =~ ^-[it]+$ ]] && show_usage
            ;;
    -*)
            show_usage
            ;;
    *)
            break
            ;;
    esac
    shift
done

if [[ $# == 0 && ! $OPT_INTERACTIVE && ! $OPT_TTY ]]; then
    OPT_INTERACTIVE=-i
    OPT_TTY=-t
fi

[[ $IS_DOCKER_GEEK ]] && exec nsenter-host "$@"

exec docker run --rm $OPT_INTERACTIVE $OPT_TTY \
    --privileged --userns=host \
    --pid=host --network=host --ipc=host --uts=host \
    -e SHELL=/bin/sh \
    osexp2000/nsenter-host "$@"
