#!/bin/bash
set -o errexit -o pipefail

function show_usage() {
  >&2 echo "Show rootfs of a container."
  >&2 echo ""
  >&2 echo "Usage:"
  >&2 echo "  ${0##*/} [CONTAINER_ID_OR_NAME]"
  >&2 echo "  docker ps | ${0##*/}"
  >&2 echo ""
  >&2 echo "Note:"
  >&2 echo "  - If CONTAINER_ID_OR_NAME is omitted, it reads each line from input, echo it,"
  >&2 echo "    grep out an 12 or 64 chars lowercase hex id, if found then process the id"
  >&2 echo "    and show result with '  rootfs: ' prepended."
  >&2 echo ""
  exit 1
}

while [[ $# > 0 ]]; do
  case $1 in
  -*)
    show_usage
    ;;
  *)
    break
    ;;
  esac
  shift
done

ID=$1

if [[ $ID ]]; then
  exec docker container inspect -f '{{.GraphDriver.Data.MergedDir}}' "$ID"
else
  while IFS='' read -r line; do
    echo "$line"
    [[ $line =~ ^"  "[a-z]+:$ ]] && continue
    ID=""
    read -a a <<<"$line"
    for x in "${a[@]}"; do
      [[ $x =~ ^[0-9a-f]{12}$ || $x =~ ^[0-9a-f]{64}$ ]] && ID=$x && break
    done
    if [[ $ID ]] && ROOTFS=$(docker container inspect -f '{{.GraphDriver.Data.MergedDir}}' "$ID" 2>/dev/null); then
      echo "  rootfs: $ROOTFS"
    fi
  done
fi
