#!/bin/bash
set -o errexit -o pipefail

function show_usage() {
  >&2 echo "Run a command or sh on behalf of the host's dockerd or init process."
  >&2 echo ""
  >&2 echo "Usage:"
  >&2 echo "  ${0##*/} [OPTIONS] [COMMAND [ARGS...]]"
  >&2 echo ""
  >&2 echo "OPTIONS:"
  >&2 echo "  -1                                   Enter the init process's all namespaces"
  >&2 echo ""
  >&2 echo "Note:"
  >&2 echo "  - If no any argument specified, it will run an interactive /bin/sh."
  >&2 echo ""
  exit 1
}

OPT_PID1=""

while [[ $# -gt 0 ]]; do
  case $1 in
  -1)
    OPT_PID1=$1
    ;;
  -*)
    show_usage
    ;;
  *)
    break
    ;;
  esac
  shift
done

if [[ $IS_DOCKER_GEEK ]]; then
  if [[ $OPT_PID1 ]]; then
    HOST_PID=1
  else
    HOST_PID=$(cat /var/run/docker.pid)
  fi
  SHELL=/bin/sh exec nsenter --target $HOST_PID --all -- "$@"
else
  exec docker-geek "${0##*/}" $OPT_PID1 "$@"
fi
