#!/bin/bash
set -o errexit -o pipefail

function show_usage() {
  >&2 echo "Start a docker-geek in which mount a container to /rootfs and switch to its network namespace."
  >&2 echo ""
  >&2 echo "Usage:"
  >&2 echo "  ${0##*/} [OPTIONS] CONTAINER_ID_OR_NAME [COMMAND [ARGS...]]"
  >&2 echo ""
  >&2 echo "OPTIONS:"
  >&2 echo "  -i, --interactive                    Keep STDIN open even if not attached"
  >&2 echo "  -t, --tty                            Allocate a pseudo-TTY"
  >&2 echo ""
  >&2 echo "Note:"
  >&2 echo "  - If no any argument specified, it will run an interactive /bin/bash (implies '-i' and '-t')."
  >&2 echo "  - You can pass extra docker run option via env var DOCKER_GEEK_OPTION"
  >&2 echo ""
  exit 1
}

OPT_INTERACTIVE=""; OPT_TTY=""

while [[ $# > 0 ]]; do
  case $1 in
  -i|--interactive)
    OPT_INTERACTIVE=$1
    ;;
  -t|--tty)
    OPT_TTY=$1
    ;;
  -*)
    [[ ! $1 =~ ^-[it]+$ ]] && show_usage
    [[ $1 == *i* ]] && OPT_INTERACTIVE=-i
    [[ $1 == *t* ]] && OPT_TTY=-t
    ;;
  *)
    break
    ;;
  esac
  shift
done

ID=${1:?${0##*/}: require next argument as an id or name of an container}; shift

if [[ $# == 0 && ! $OPT_INTERACTIVE && ! $OPT_TTY ]]; then
  OPT_INTERACTIVE=-i
  OPT_TTY=-t
fi

if ! PID=$(docker-pid-of-container "$ID"); then
  exec docker-image-geek $OPT_INTERACTIVE $OPT_TTY "$ID" "$@"
fi

ROOTFS=$(docker-rootfs-of-container "$ID")

[[ ! $ID =~ ^[0-9a-f]{12}$ && ! $ID =~ ^[0-9a-f]{64}$ ]] && ID=$(docker container inspect -f '{{.ID}}' "$ID")

[[ $# == 0 ]] && set -- bash -l

export DOCKER_GEEK_NETWORK_OPTION="--network=container:$ID"
export DOCKER_GEEK_OPTION="$DOCKER_GEEK_OPTION -v $ROOTFS:/rootfs.no_sub_mounts"
exec docker-geek $OPT_INTERACTIVE $OPT_TTY sh -c \
  "ln -s /proc/$PID/root /rootfs && cd /rootfs && exec \"\$@\"" \
    -- "$@"
