#!/bin/bash
set -o errexit -o pipefail

[[ ! $IS_DOCKER_GEEK ]] && exec docker-geek "${0##*/}" "$@"

[[ -e /sys/kernel/debug/tracing ]] || mount -t debugfs debugfs /sys/kernel/debug
exec opensnoop "$@"
