#!/bin/bash
set -o errexit -o pipefail
export MSYS_NO_PATHCONV=1

function show_usage() {
  >&2 echo "Run a privileged tool container in the host's network namespace."
  >&2 echo ""
  >&2 echo "Usage:"
  >&2 echo "  ${0##*/} [COMMAND [ARGS...]]"
  >&2 echo "  ${0##*/} --update"
  >&2 echo ""
  >&2 echo "Note:"
  >&2 echo "  - If no any argument specified, it will run an interactive /bin/bash."
  >&2 echo "  - You can pass extra docker run option via env var DOCKER_GEEK_OPTION"
  >&2 echo ""
  exit 1
}

if [[ $1 == --update ]]; then
  set -x # show command trace
  docker pull osexp2000/docker-geek
  cd "$(dirname $(which docker-geek))"
  git fetch
  git reset --hard origin/master
  exit
fi

OPT_TTY=""; [[ -t 0 ]] && OPT_TTY=--tty

if [[ $(docker info --format '{{.OperatingSystem}}') == 'Docker Desktop' ]]; then
  DOCKER_SOCK_PATH=/run/desktop/docker.sock
  DOCKER_PID_PATH=/run/desktop/docker.pid
else
  DOCKER_SOCK_PATH=/var/run/docker.sock
  DOCKER_PID_PATH=/var/run/docker.pid
fi

MOUNT_OVERLAY_ROOT=""
if [[ $(docker info --format '{{.Driver}}') == overlay* ]]; then
  MOUNT_OVERLAY_ROOT="-v /var/lib/docker:/var/lib/docker:rshared"
fi

if [[ ! $DOCKER_GEEK_NETWORK_OPTION ]]; then
  DOCKER_GEEK_NETWORK_OPTION='--network=host --hostname=GEEK --add-host GEEK:127.0.0.1'
fi

# Notes:
# - The --add-host GEEK:127.0.0.1 is for avoiding sudo from warning about host can not be resolved.
# - The /var/run/docker.sock is for using docker client in the docker-geek
# - The /var/run/docker.pid is for getting dockerd's pid in the docker-geek
# - The /var/lib/docker is for mounting containers or images because their actual contents is there
# - The /var/lib/docker mount point will be rshared propagation type, so that new mounts
#   inside docker-geek will be propagated to the host, hence indirectly to target container

exec docker run --rm --interactive $OPT_TTY \
  --privileged --userns=host --pid=host --ipc=host \
  $DOCKER_GEEK_NETWORK_OPTION \
  -v $DOCKER_SOCK_PATH:/var/run/docker.sock \
  -v $DOCKER_PID_PATH:/var/run/docker.pid \
  $MOUNT_OVERLAY_ROOT \
  -v /:/host-rootfs \
  --workdir="/host-rootfs"  \
  $DOCKER_GEEK_OPTION \
  osexp2000/docker-geek "$@"
