#!/bin/bash
set -o errexit -o pipefail

LAYERS=${1:?"expect an argument as LAYERS which is a comma separated dirs"}; shift
MOUNT_POINT=${1:?"expect an argument as MOUNT_POINT which is an target dir where to mount"}; shift

[[ ! -d "$MOUNT_POINT" ]] && mkdir -p "$MOUNT_POINT"

if [[ $LAYERS == *:* ]]; then
    mount -t overlay overlay "$MOUNT_POINT" -o lowerdir="$LAYERS"
else
    mount -o bind,ro "$LAYERS" "$MOUNT_POINT"
fi

cd "$MOUNT_POINT"
[[ $# != 0 ]] && exec "$@"
